name: the_game
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  email_validator: ^2.1.17
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.1
  url_launcher: ^6.1.11
  dio: ^5.1.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  geolocator: ^9.0.2
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.1.1
  google_maps_flutter: ^2.2.7
  gallery_saver: ^2.3.2
  photo_view: ^0.14.0
  geocoding: ^2.1.0
  http_parser: ^4.0.2
  flutter_local_notifications: ^14.1.1
  share_plus: ^7.2.1
  firebase_dynamic_links: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true